#!/sbin/ash

mknod /dev/null    c 1 3
mknod /dev/ptmx    c 4 2
mknod /dev/ram0    b 1 0
mknod /dev/tty0    c 5 0
mknod /dev/ttyS0   c 4 64

mount /proc
mount /sys

PATH=/sbin

export NCPUS=`grep processor /proc/cpuinfo | wc -l`

echo Number of CPUs: $NCPUS | /sbin/qsim_out

cd data

echo "Start Simulation"
# START Simulation
/sbin/mark_app

echo "In Simulation 1"
echo "In Simulation 2"
echo "In Simulation 3"
echo "In Simulation 4"
echo "In Simulation 5"
echo "In Simulation 6"
echo "In Simulation 7"
echo "In Simulation 8"
echo "In Simulation 9"
echo "In Simulation 10"


echo --- program exit, will shutdown shortly... ---
/sbin/mark_app "END"


# Spin forever.
while true; do
  sleep 10
done
