language: cpp
sudo: false
addons:
    apt:
        sources:
        - ubuntu-toolchain-r-test
        packages:
        - g++-4.8
        - clang-3.4
        - bc
before_install:
    - git submodule update --init --recursive
    - export QSIM_PREFIX=`pwd`
    - export LD_LIBRARY_PATH=$QSIM_PREFIX/lib:$LD_LIBRARY_PATH
    - cd capstone
    - make
    - cd ..
    - cd distorm/distorm64/build/linux
    - make clib
    - cd $QSIM_PREFIX/linux
    - ./getkernel.sh
    - cd $QSIM_PREFIX/initrd
    - ./getbusybox.sh
    - cd $QSIM_PREFIX
script:
    - make release install
    - make tests
after_success:
    - cd $QSIM_PREFIX/examples/x86/
    - make
    - cd $QSIM_PREFIX/examples/arm64/
    - make
compiler:
- clang
- gcc
git:
  submodules: true
notifications:
    email:
        recipients:
            - bobby.prani@gmail.com
        on_success: change
        on_failure: always
    irc: "irc.oftc.net#qsim"
