language: cpp
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test  # gcc v4.8
    - sudo apt-get -qq update
    - sudo apt-get install -qq g++-4.8
    - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
    - if [ "$CC" = "clang" ]; then sudo apt-get install -qq clang-3.4; fi
    - sudo apt-get build-dep qemu
    - git submodule update --init --recursive
    - export QSIM_PREFIX=`pwd`
    - mkdir build
    - cd build
    - ../arm64-build.sh release
    - cd ..
    - cd capstone
    - make
    - cd ..
    - cd distorm/distorm64/build/linux
    - make clib
    - cd ../../../..
script:
    - make -j2
install:
    - make install
after_success:
    - cd examples/x86/
    - make
    - cd ../arm64/
    - make
compiler:
- clang
- gcc
git:
  submodules: true
notifications:
    email:
        recipients:
            - bobby.prani@gmail.com
        on_success: change
        on_failure: always
