language: c
before_install:
    - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test  # gcc v4.8
    - sudo apt-get -qq update
    - if [ "$CC" = "gcc" ]; then sudo apt-get install -qq g++-4.8; fi
    - if [ "$CC" = "gcc" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90; fi
    - if [ "$CC" = "clang" ]; then sudo apt-get install -qq clang-3.4; fi
    - sudo apt-get build-dep qemu
    - git submodule update --init --recursive
    - export QSIM_PREFIX=`pwd`
    - mkdir build
    - cd build
    - ../arm64-build.sh release
    - cd ..
script:
    - make -j2
install:
    - make install
compiler:
- clang
- gcc
git:
  submodules: true
notifications:
    email:
        recipients:
            - bobby.prani@gmail.com
        on_success: change
        on_failure: always
